End fishing CMD and Lore edits
Gamemode4Dev/GM4_Datapacks pull request #507
Opened 2020-12-29 08:04 UTC by hozz8528

This does the following:
- Changes the name of the Elytra dropped by End Fishing phantoms to Raptured Wings and gives them Custom Model Data (11)
- Gives the ultra rare elytra you get directly from fishing in certain biomes Custom Model Data (10) and lore (Nobody imagined the Captain's lost wings would be seen again, ever.)
- Fixes some punctuation, grammatical, capitalization errors and typos in the lore for end city treasure, as well as shortening some of them to reduce the size of the item box

2020-12-29 08:13 UTC, BluePsychoRanger approved these changes
Looks good. These changes won't break anything (notably the sword advancement). so it should be fine to update these lores.

2021-01-05 01:25 UTC, misode requested changes

2021-01-05 01:25 UTC, misode commented on gm4_end_fishing/data/gm4_end_fishing/loot_tables/entities/end_phantom.json
> +					"text": "Raptured Wings",
Name isn't translatable

2021-01-05 01:32 UTC, misode approved these changes

2021-01-05 01:33 UTC, merged