Speed Paths' speed boost: potion effect -> attribute modifier
Gamemode4Dev/GM4_Datapacks pull request #518
Opened 2021-02-07 06:21 UTC by EpyonProjects

Making the speed boost an attribute modifier allows the player to stack additional speed effects (vanilla potions or beacons, and Zauber speed armor)

2021-02-07 06:58 UTC, BluePsychoRanger commented on gm4_speed_paths/data/gm4_speed_paths/functions/main.mcfunction
> +execute as @a at @s run attribute @s minecraft:generic.movement_speed modifier remove dc33007e-5da4-4fad-a850-9c5a058c22ba
```suggestion
execute as @a run attribute @s minecraft:generic.movement_speed modifier remove dc33007e-5da4-4fad-a850-9c5a058c22ba
```

2021-02-14 20:45 UTC, misode requested changes
The current implementation gives the speed effect for 2 seconds for lag and jumping reasons. If attributes are used it needs a similar measurement.

2021-04-17 11:59 UTC, misode commented
@EpyonProjects After a few modifications we'd be happy to merge this. 
1. The module didn't have particles before, so it shouldn't artificially be added
2. The duration of the effect is a bit too long, it should be just enough so you keep the effect when jumping on paths with lag. Before the effect was given for 2 seconds and that seemed to work.
2.1. Any reason the scoreboard counts in increments of 5?

2021-04-17 17:43 UTC, SpecialBuilder32 approved these changes
Tested and Approved

2021-04-18 01:06 UTC, merged