Added downward movement for Vertical Rails
Gamemode4Dev/GM4_Datapacks pull request #536
Opened 2021-03-05 23:18 UTC by EpyonProjects

2021-03-11 15:07 UTC, Bloo-dev requested changes

2021-03-11 15:07 UTC, Bloo-dev commented on gm4_vertical_rails/data/gm4_vertical_rails/functions/rail/check_direction.mcfunction
> +execute as @s[tag=!gm4_vert_rail_down] at @s if block ~ ~1 ~ ladder run tag @s add gm4_vert_rail_up
```suggestion
execute if entity @s[tag=!gm4_vert_rail_down] if block ~ ~1 ~ ladder run tag @s add gm4_vert_rail_up
```
The function is already being called `as @s at @s` and no changes to the position of `@s` are made during the function, therefore `at @s` may be omitted to make this function run faster. Usage of `if entity @s` will also speed up the function in comparison to reselecting the frame of reference to `as @s`.

2021-03-11 15:07 UTC, Bloo-dev commented on gm4_vertical_rails/data/gm4_vertical_rails/functions/rail/check_direction.mcfunction
> +execute as @s[tag=!gm4_vert_rail_up] at @s if block ~ ~-1 ~ ladder unless block ~ ~1 ~ ladder run tag @s add gm4_vert_rail_down
```suggestion
execute if entity @s[tag=!gm4_vert_rail_up] if block ~ ~-1 ~ ladder unless block ~ ~1 ~ ladder run tag @s add gm4_vert_rail_down
```
The function is already being called `at @s` and no changes to the position of `@s` are made during the function, therfore `at @s` may be ommited to make this function run faster. Usage of `if entity @s` will also speed up the function in comparison to reselecting the frame of reference to `as @s`.

2021-03-11 15:07 UTC, Bloo-dev commented on gm4_vertical_rails/data/gm4_vertical_rails/functions/rail/apply_direction.mcfunction
> +execute as @s[tag=gm4_vert_rail_down] at @s unless block ~ ~-1 ~ ladder run function gm4_vertical_rails:rail/downward/detach_ladder
The amount of reference frame changes in this function can be reduced to 0. See my comments attached to `check_direction.mcfunction`.
The momentum changes shouldn't alter the carts position until the next tick, so re-calling `at @s` shouldn't be necessary.

2021-03-11 15:07 UTC, Bloo-dev commented on gm4_vertical_rails/data/gm4_vertical_rails/functions/process.mcfunction
> +execute as @s at @s unless block ~ ~ ~ ladder run function gm4_vertical_rails:rail/clear_tags
Reduce the amount of reference frame changes; View my comment on `check_direction.mcfunction`.

2021-03-22 01:46 UTC, EpyonProjects commented
Dropping this :')

2021-03-22 01:46 UTC, closed without merging