Translation path fixes (mostly)
Gamemode4Dev/GM4_Datapacks pull request #577
Opened 2021-05-04 07:38 UTC by hozz8528

- Changed a few translation paths to be more in line with the rest of modules (changed an item. to text., added the name of the module to the path in some cases, etc.)
- Added a few missing translation paths (and fixed 1 broken one)
- Added section symbols (and 1 CMD) to Orb of Ankou mobs to allow for retexturing since I was already modifying those files anyways.

2021-05-04 07:44 UTC, BluePsychoRanger approved these changes
Looks good, though have you looked through every module for incorrect translation keys?

2021-05-05 12:52 UTC, misode requested changes

2021-05-05 12:52 UTC, misode commented on gm4_zauber_liquids/data/gm4_zauber_liquids/functions/liquid_init/harming.mcfunction
> +data merge block ~ ~ ~ {CustomName:'{"translate":"%1$s%3427655$s","with":["Zauber Harming Potion Tank", {"translate":"block.gm4.zauber_liquids.harming"}]}'}
To be consistent with potion tanks, the translation key should be `block.gm4.zauber_tank.harming`. See https://github.com/Gamemode4Dev/GM4_Resources/blob/master/gm4_translations/assets/gm4/lang/en_us.json#L111

2021-05-05 12:52 UTC, misode commented on gm4_everstone/data/gm4_everstone/loot_tables/everstone.json
> +							"with": [
Mixed tabs and spaces. I know we aren't always consistent, but at least consistency on a file base would be nice.

2021-06-01 21:12 UTC, misode approved these changes

2021-06-01 21:45 UTC, merged