Villager Telltale Module
Gamemode4Dev/GM4_Datapacks pull request #580
Opened 2021-05-05 21:15 UTC by MichaelMiner137

Features
- When holding a work block near a villager they will look at their job site and particles will be displayed
- The same effect will happen when holding a bell or bed
- If the site of interest is missing then a barrier particle will be displayed

Notes
- If the villagers bell or bed is broken the nbt will not change so they will look at the last known location

2021-05-05 22:02 UTC, BluePsychoRanger requested changes
This looks like a good module. However there are some optimizations to be made, especially utilizing predicates for the mainhand check. What happens if the villager doesn't have a bed/workstation/bell? Do they still look somewhere?

2021-05-05 22:02 UTC, BluePsychoRanger commented on gm4_villager_telltale/data/gm4/advancements/vt_find_workstation.json
> +{
This advancement should be named more consistently with the rest of GM4 modules. Modules with only a single advancement should be named their own module name. (So this should be renamed to `villager_telltale`)

2021-05-05 22:08 UTC, BluePsychoRanger commented on gm4_villager_telltale/data/gm4_villager_telltale/functions/main.mcfunction
> +execute as @a at @s run function gm4_villager_telltale:player
Correction, you need 3 item tags cuz you don't need an item tag for just the bell. The "all" item tag will just use the other two item tags, plus the bell.

2021-05-05 23:04 UTC, MichaelMiner137 commented on gm4_villager_telltale/data/gm4_villager_telltale/functions/villager/locate_bed.mcfunction
> +execute if data storage gm4_villager_telltale:temp/villager Look[2] run function gm4_villager_telltale:villager/begin_looking
yes, it is checking if their is a job/bed/bell

2021-05-06 05:00 UTC, BluePsychoRanger commented on gm4_villager_telltale/data/gm4_villager_telltale/functions/main.mcfunction
> +tag @a remove gm4_tv_holding_villager_block
This tag should be removed at the end of the `player` function. There's no reason to run it every clock cycle.

2021-05-06 05:01 UTC, BluePsychoRanger commented on gm4_villager_telltale/data/gm4_villager_telltale/functions/main.mcfunction
> +tag @a remove gm4_tv_holding_villager_block
Also why is it `tv` instead of `vt`?

2021-05-11 21:57 UTC, closed without merging