Add Iacio Shamir (throw further)
Gamemode4Dev/GM4_Datapacks pull request #596
Opened 2021-05-20 13:19 UTC by Dennis-0

Barium shamir for chestplate - Amplify your throwing power

Items thrown with this shamir equipped will have their motion multiplied by 2:
- Ender pearl
- Snowball
- Egg
- Potion (splash and lingering)
- Any item

Note: This does not work in creative mode because it uses the `inventory_changed` advancement

2021-05-20 18:32 UTC, BluePsychoRanger approved these changes
I like this module and it's well optimized! Why isn't tridents on this list though? I feel like the most useful projectile would be tridents

2021-05-20 18:32 UTC, BluePsychoRanger commented on gm4_iacio_shamir/data/gm4_iacio_shamir/functions/check_throw.mcfunction
> +#run from advancement
the header should say which advancement

2021-05-20 18:32 UTC, BluePsychoRanger commented on gm4_iacio_shamir/data/gm4_iacio_shamir/functions/check_throw.mcfunction
> +execute as @e[type=item,distance=..2,nbt={Age:0s},limit=1] at @s run function gm4_iacio_shamir:add_motion
why don't you check a drop score here?

2021-06-04 10:42 UTC, Bloo-dev requested changes
This is a very neat shamir. This is some very optimized and minimal code, well done.
Please resolve the comment I left.

2021-06-04 10:42 UTC, Bloo-dev commented on gm4_iacio_shamir/data/gm4_iacio_shamir/functions/init.mcfunction
> +scoreboard objectives add gm4_ml_iacio_lp minecraft.used:minecraft.lingering_potion
`ml_` shouldn't be used as a prefix unless code is part of the metallurgy base.  This change needs to be made in multiple sections of code throughout the module.

2021-06-04 12:54 UTC, Bloo-dev approved these changes
This will now advance to server testing.

2021-06-04 18:13 UTC, SandSander approved these changes

2021-06-24 10:53 UTC, merged