Barimium Shamir for Shields - Heal when blocking
Gamemode4Dev/GM4_Datapacks pull request #608
Opened 2021-06-03 23:00 UTC by EpyonProjects

In addition to blocking damage when using a shield, heal 1.5 hearts

2021-06-04 03:36 UTC, BluePsychoRanger approved these changes
Looks good. You should add the pack.png and pack.svg tho

2021-06-04 03:36 UTC, BluePsychoRanger commented on gm4_vigere_shamir/pack.mcmeta
> +                "https://twitter.com/The_Thanathor"
Did Epyon not also help create this Shamir?

2021-06-04 22:45 UTC, Bloo-dev requested changes
This looks good overall. There are three minor things that need to be resolved:

- [x] `$` on fake player
- [ ] Use `gm4_ml_data`
- [ ] implement Lue's player heads (see example a) below)


a) You'll need to make a minor change to the loot table `band.json` and add a line to `init.mcfunction`:
![changes](https://user-images.githubusercontent.com/41843855/120869485-e0126400-c596-11eb-84fc-c4d7a0f5d3af.png)
Here are two example files:
- [init.mcfunction](https://github.com/Gamemode4Dev/GM4_Datapacks/blob/0b36bc7f7eef1b4987cf3025e0e3f4ad37ca8f7d/gm4_percurro_shamir/data/gm4_percurro_shamir/functions/init.mcfunction)
- [band.json](https://github.com/Gamemode4Dev/GM4_Datapacks/blob/0b36bc7f7eef1b4987cf3025e0e3f4ad37ca8f7d/gm4_percurro_shamir/data/gm4_percurro_shamir/loot_tables/band.json)
**Remember to** update the band type, color of the lore text, translation key and metal amounts to suit your shamir. You can cross check with some other shamirs like celaro, vecto, audere or helious to get some more examples.

2021-06-04 22:45 UTC, Bloo-dev commented on gm4_vigere_shamir/data/gm4_vigere_shamir/functions/heal.mcfunction
> +execute if score remove_health gm4_vs_data matches 512.. run attribute @s minecraft:generic.max_health modifier add e0c18b32-4caf-4193-8899-74ad1cc0dba2 gm4_vs_remove_512 -512 add
Fake players should use `$`, so `$remove_health`.

2021-06-04 22:45 UTC, Bloo-dev commented on gm4_vigere_shamir/data/gm4_vigere_shamir/functions/heal.mcfunction
> +execute if score remove_health gm4_vs_data matches 1.. run scoreboard players remove remove_health gm4_vs_data 1
You could reuse the objective `gm4_ml_data`, as metallurgy will always be installed alongside this.

2021-06-07 11:02 UTC, Bloo-dev requested changes

2021-06-07 11:02 UTC, Bloo-dev commented on gm4_vigere_shamir/data/gm4_metallurgy/tags/functions/update_skull_owner.json
> +}
You don't need this file as your Shamir was created - and will therefore be merged - after PR #593. This is only required to update data on items created before that PR.

2021-06-07 11:02 UTC, Bloo-dev commented on gm4_vigere_shamir/data/gm4_vigere_shamir/functions/update_skull_owner.mcfunction
> + execute if data storage gm4_metallurgy:temp/shamir {name:"vigere"} run data modify storage gm4_metallurgy:temp/shamir skull_owner set value "[Drop to Fix Item] gm4_vigere_shamir:band/v0"
You don't need this file as your Shamir was created - and will therefore be merged - after PR #593. This is only required to update data on items created before that PR.

2021-07-05 15:23 UTC, Bloo-dev approved these changes
All requested changes were implemented, looks good to me.

2021-07-05 15:52 UTC, Bloo-dev requested changes
After further testing in `1.17.1-rc2` we got 2 leftover hearts from this module. Further testing is required.

2021-08-10 10:27 UTC, Bloo-dev approved these changes
The leftover hearts seem to be a Minecraft bug. We'll keep an eye on this but this won't prevent this PR from being merged.

2021-08-20 11:55 UTC, Bloo-dev approved these changes
Tested in game and code-reviewed.

2021-08-20 11:57 UTC, merged