Particles Pack: More particles
Gamemode4Dev/GM4_Datapacks pull request #616
Opened 2021-06-23 20:36 UTC by Dennis-0

As requested by BartTheBart, some new particles that could add a lot to certain themes.
I understand that it might be a bit much to have double the amount of particles, but at least some of these would be great to have (like blossom, lava, enchant etc.)

Falling dust:
- Blossom (pink)
- Autumn (orange and brown)
- Spring (lime)
- Winter (white)
- Ash (black)

Other:
- Lava
- Fiesta (totem of undying)
- Confetti (fountain shooting totem of undying particles)
- Ender (portal particles towards armour stand)
- Enchant (enchant particles towards armour stand)

2021-07-06 20:15 UTC, SpecialBuilder32 commented
Would PR #617 replace the features introduced here, or would it be another additional option for types of particles?

2021-07-06 20:19 UTC, Dennis-0 commented
> Would PR #617 replace the features introduced here, or would it be another additional option for types of particles?

That PR is mostly about the idea, but in case that PR is accepted, we should have a look which of the hardcoded particles are worth keeping. 
So it would be additional particles, not necessarily replacing them

2021-07-11 17:04 UTC, SpecialBuilder32 approved these changes
Tested and all these work as expected. I think the sizes and particle counts look pretty good too.

2021-08-20 13:27 UTC, Bloo-dev requested changes
We looked at these changes in game and have some requests:

- remove the `confetti` particle
- remove `snow` or make `snow` and alias for winter

2021-08-20 18:34 UTC, Bloo-dev approved these changes

2021-08-20 18:34 UTC, merged