Added Glow Squid to Ink Spitting Squid
Gamemode4Dev/GM4_Datapacks pull request #620
Opened 2021-06-28 03:44 UTC by EpyonProjects

* an additional advancement for glow squids
* changed two block tag checks into one water predicate

2021-07-06 19:45 UTC, SpecialBuilder32 requested changes
Tested and it works as expected.

2021-07-06 19:45 UTC, SpecialBuilder32 commented on gm4_ink_spitting_squid/data/gm4/advancements/glow_ink_spitting_squid.json
> +  "parent": "gm4:root",
I would recommend making this a child of the normal squid advancement, and perhaps making it a "goal" type frame as glow squids are slightly more rare

2021-07-11 16:07 UTC, SpecialBuilder32 approved these changes

2021-07-17 17:21 UTC, merged

2021-07-22 01:57 UTC, BluePsychoRanger commented on gm4_ink_spitting_squid/data/gm4_ink_spitting_squid/predicates/in_water.json
> +      "fluid": "minecraft:water"
this should've been `"tag": "minecraft:water"`. `"fluid"` makes it only work with source blocks