Zauber Cauldrons 1.17
Gamemode4Dev/GM4_Datapacks pull request #627
Opened 2021-07-09 16:41 UTC by Bloo-dev

### Feature Changes
This update brings some new features to Zauber Cauldrons, mainly allowing Zauber Cauldrons to use powder snow as a liquid.
Powder snow provides additional cooling, making some more exothermic recipes safe! This means:
- [ ] Powder snow makes the use of splash or lingering potions in tier IV potion recipes safe. This allows you to craft tier IV splash and lingering potions
- [ ] Powder snow prevents tier IV strength potions from causing fire

In addition to that, there are also some minor changes to features such as:

- [ ] Crafting a tier IV poison potion now uses a better source of randomness for the placement of cave spiders and cobwebs
- [ ] Balance changes to Zauber Armor's attribute values
- [ ] Changes to Zauber  Armor crafting ingredients
- [ ] Changes to Zauber Crystal crafting ingredients
- [ ] Changes to Zauber Crystal texture
- [ ] Magic in a bottle take longer to break and telegraph the breaking before they do
- [ ] Campfires can be used to heat Zauber Cauldrons

### Technical Changes
This update completely reworks the Zauber Cauldrons' crafting system in order to make it loot table based. This will make it easier for other modules to interact with Zauber Cauldrons and allow for easier debugging // creative play.

- [ ] Rework Zauber Potions crafting
- [ ] Rework Zauber Armor crafting
- [ ] Rework Zauber Crystals crafting
- [ ] Rework Prismarine Shard crafting
- [ ] Rework Flower Luck crafting
- [ ] Rework Wormhole crafting
- [ ] Rework Multi-Sip crafting

In addition to the changes to the crafting system, some parameters for crafting are now dynamic, allowing for more cross-module interactions - especially for liquid tanks.

- [ ] Allow arbitrary amounts of sips per bottle
- [ ] Allow remote execution of recipes, both with soul and normal fire

Efficiency of Zauber Cauldrons has also improved, especially in worlds with lots of entities. The new crafting system no longer uses `@e` selectors to detect ingredients; instead they refer to a data storage. Zauber Cauldrons' fake players are now prefix according to Gamemode 4's style guide.

**PLEASE NOTE THAT THIS A DRAFT PR**

2021-07-18 05:19 UTC, BluePsychoRanger requested changes
I was looking over the loot tables, and I noticed you did the potion effects lore incorrectly (and a few typos). I've left suggestion comments to correctly display the potion effects correctly.

2021-07-18 05:19 UTC, BluePsychoRanger commented on gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/loot_tables/recipes/potions/lingering/instant_damage.json
> +                            ],
```suggestion
                            "lore": [
                                [
                                    {
                                        "translate": "potion.withAmplifier",
                                        "with": [
                                            {
                                                "translate": "effect.minecraft.instant_damage"
                                            },
                                            {
                                                "translate": "potion.potency.3"
                                            }
                                        ],
                                        "color": "red",
                                        "italic": false
                                    }
                                ]
                            ],
```

2021-07-18 05:19 UTC, BluePsychoRanger commented on gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/loot_tables/recipes/potions/drinkable/instant_damage.json
> +                            ],
```suggestion
                            "lore": [
                                [
                                    {
                                        "translate": "potion.withAmplifier",
                                        "with": [
                                            {
                                                "translate": "effect.minecraft.instant_damage"
                                            },
                                            {
                                                "translate": "potion.potency.3"
                                            }
                                        ],
                                        "color": "red",
                                        "italic": false
                                    }
                                ]
                            ],
```

2021-07-18 05:19 UTC, BluePsychoRanger commented on gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/loot_tables/recipes/potions/lingering/instant_health.json
> +                            ],
```suggestion
                            "lore": [
                                [
                                    {
                                        "translate": "potion.withAmplifier",
                                        "with": [
                                            {
                                                "translate": "effect.minecraft.instant_health"
                                            },
                                            {
                                                "translate": "potion.potency.3"
                                            }
                                        ],
                                        "color": "blue",
                                        "italic": false
                                    }
                                ],
                                [
                                    {
                                        "translate": "potion.withDuration",
                                        "with": [
                                            {
                                                "translate": "effect.minecraft.nausea"
                                            },
                                            "0:02"
                                        ],
                                        "color": "red",
                                        "italic": false
                                    }
                                ]
                            ],
```

2021-07-18 05:19 UTC, BluePsychoRanger commented on gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/loot_tables/recipes/potions/lingering/jump_boost.json
> +                            ],
```suggestion
                            "lore": [
                                [
                                    {
                                        "translate": "potion.withDuration",
                                        "with": [
                                            {
                                                "translate": "potion.withAmplifier",
                                                "with": [
                                                    {
                                                        "translate": "effect.minecraft.jump_boost"
                                                    },
                                                    {
                                                        "translate": "potion.potency.3"
                                                    }
                                                ]
                                            },
                                            "0:22"
                                        ],
                                        "color": "blue",
                                        "italic": false
                                    }
                                ]
                            ],
```

2021-07-18 05:19 UTC, BluePsychoRanger commented on gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/loot_tables/recipes/potions/lingering/poison.json
> +                            ],
```suggestion
                            "lore": [
                                [
                                    {
                                        "translate": "potion.withDuration",
                                        "with": [
                                            {
                                                "translate": "potion.withAmplifier",
                                                "with": [
                                                    {
                                                        "translate": "effect.minecraft.poison"
                                                    },
                                                    {
                                                        "translate": "potion.potency.3"
                                                    }
                                                ]
                                            },
                                            "0:08"
                                        ],
                                        "color": "red",
                                        "italic": false
                                    }
                                ]
                            ],
```

2021-07-18 05:19 UTC, BluePsychoRanger commented on gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/loot_tables/recipes/potions/lingering/regeneration.json
> +                            ],
```suggestion
                            "lore": [
                                [
                                    {
                                        "translate": "potion.withDuration",
                                        "with": [
                                            {
                                                "translate": "potion.withAmplifier",
                                                "with": [
                                                    {
                                                        "translate": "effect.minecraft.regeneration"
                                                    },
                                                    {
                                                        "translate": "potion.potency.3"
                                                    }
                                                ]
                                            },
                                            "0:05"
                                        ],
                                        "color": "blue",
                                        "italic": false
                                    }
                                ],
                                [
                                    {
                                        "translate": "potion.withDuration",
                                        "with": [
                                            {
                                                "translate": "potion.withAmplifier",
                                                "with": [
                                                    {
                                                        "translate": "effect.minecraft.speed"
                                                    },
                                                    {
                                                        "translate": "potion.potency.2"
                                                    }
                                                ]
                                            },
                                            "0:04"
                                        ],
                                        "color": "blue",
                                        "italic": false
                                    }
                                ]
                            ],
```

2021-07-18 05:19 UTC, BluePsychoRanger commented on gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/loot_tables/recipes/potions/lingering/speed.json
> +                            ],
```suggestion
                            "lore": [
                                [
                                    {
                                        "translate": "potion.withDuration",
                                        "with": [
                                            {
                                                "translate": "potion.withAmplifier",
                                                "with": [
                                                    {
                                                        "translate": "effect.minecraft.speed"
                                                    },
                                                    {
                                                        "translate": "potion.potency.3"
                                                    }
                                                ]
                                            },
                                            "0:50"
                                        ],
                                        "color": "blue",
                                        "italic": false
                                    }
                                ],
                                [
                                    {
                                        "translate": "potion.withDuration",
                                        "with": [
                                            {
                                                "translate": "potion.withAmplifier",
                                                "with": [
                                                    {
                                                        "translate": "effect.minecraft.weakness"
                                                    },
                                                    {
                                                        "translate": "potion.potency.3"
                                                    }
                                                ]
                                            },
                                            "1:30"
                                        ],
                                        "color": "blue",
                                        "italic": false
                                    }
                                ],
                                {
                                    "text": ""
                                },
                                {
                                    "translate": "potion.whenDrank",
                                    "color": "dark_purple",
                                    "italic": false
                                },
                                {
                                    "translate": "attribute.modifier.plus.1",
                                    "with": [
                                         "80",
                                         {
                                             "translate": "attribute.name.generic.movement_speed"
                                         }
                                     ],
                                     "color": "blue",
                                     "italic": false
                                },
                                {
                                    "translate": "attribute.modifier.take.0",
                                    "with": [
                                        "16",
                                        {
                                            "translate": "attribute.name.generic.attack_damage"
                                        }
                                    ],
                                    "color": "red",
                                    "italic": false
                                }
                            ],
```

2021-07-18 05:19 UTC, BluePsychoRanger commented on gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/loot_tables/recipes/potions/lingering/strength.json
> +                            ],
```suggestion
                            "lore": [
                                [
                                    {
                                        "translate": "potion.withDuration",
                                        "with": [
                                            {
                                                "translate": "potion.withAmplifier",
                                                "with": [
                                                    {
                                                        "translate": "effect.minecraft.strength"
                                                    },
                                                    {
                                                        "translate": "potion.potency.3"
                                                    }
                                                ]
                                            },
                                            "0:22"
                                        ],
                                        "color": "blue",
                                        "italic": false
                                    }
                                ],
                                {
                                    "text": ""
                                },
                                {
                                    "translate": "potion.whenDrank",
                                    "color": "dark_purple",
                                    "italic": false
                                },
                                {
                                    "translate": "attribute.modifier.plus.0",
                                    "with": [
                                        "12",
                                        {
                                            "translate": "attribute.name.generic.attack_damage"
                                        }
                                    ],
                                    "color": "blue",
                                    "italic": false
                                }
                            ],
```

2021-07-18 05:19 UTC, BluePsychoRanger commented on gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/loot_tables/recipes/potions/splash/instant_damage.json
> +                            ],
```suggestion
                            "lore": [
                                [
                                    {
                                        "translate": "potion.withAmplifier",
                                        "with": [
                                            {
                                                "translate": "effect.minecraft.instant_damage"
                                            },
                                            {
                                                "translate": "potion.potency.3"
                                            }
                                        ],
                                        "color": "red",
                                        "italic": false
                                    }
                                ]
                            ],
```

2021-07-18 05:19 UTC, BluePsychoRanger commented on gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/loot_tables/recipes/potions/splash/instant_health.json
> +                            ],
```suggestion
                            "lore": [
                                [
                                    {
                                        "translate": "potion.withAmplifier",
                                        "with": [
                                            {
                                                "translate": "effect.minecraft.instant_health"
                                            },
                                            {
                                                "translate": "potion.potency.3"
                                            }
                                        ],
                                        "color": "blue",
                                        "italic": false
                                    }
                                ],
                                [
                                    {
                                        "translate": "potion.withDuration",
                                        "with": [
                                            {
                                                "translate": "effect.minecraft.nausea"
                                            },
                                            "0:08"
                                        ],
                                        "color": "red",
                                        "italic": false
                                    }
                                ]
                            ],
```

2021-07-18 05:19 UTC, BluePsychoRanger commented on gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/loot_tables/recipes/potions/splash/jump_boost.json
> +                            ],
```suggestion
                            "lore": [
                                [
                                    {
                                        "translate": "potion.withDuration",
                                        "with": [
                                            {
                                                "translate": "potion.withAmplifier",
                                                "with": [
                                                    {
                                                        "translate": "effect.minecraft.jump_boost"
                                                    },
                                                    {
                                                        "translate": "potion.potency.3"
                                                    }
                                                ]
                                            },
                                            "1:30"
                                        ],
                                        "color": "blue",
                                        "italic": false
                                    }
                                ]
                            ],
```

2021-07-18 05:19 UTC, BluePsychoRanger commented on gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/loot_tables/recipes/potions/splash/poison.json
> +                            ],
```suggestion
                            "lore": [
                                [
                                    {
                                        "translate": "potion.withDuration",
                                        "with": [
                                            {
                                                "translate": "potion.withAmplifier",
                                                "with": [
                                                    {
                                                        "translate": "effect.minecraft.poison"
                                                    },
                                                    {
                                                        "translate": "potion.potency.3"
                                                    }
                                                ]
                                            },
                                            "0:32"
                                        ],
                                        "color": "red",
                                        "italic": false
                                    }
                                ]
                            ],
```

2021-07-18 05:19 UTC, BluePsychoRanger commented on gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/loot_tables/recipes/potions/splash/regeneration.json
> +                            ],
```suggestion
                            "lore": [
                                [
                                    {
                                        "translate": "potion.withDuration",
                                        "with": [
                                            {
                                                "translate": "potion.withAmplifier",
                                                "with": [
                                                    {
                                                        "translate": "effect.minecraft.regeneration"
                                                    },
                                                    {
                                                        "translate": "potion.potency.3"
                                                    }
                                                ]
                                            },
                                            "0:22"
                                        ],
                                        "color": "blue",
                                        "italic": false
                                    }
                                ],
                                [
                                    {
                                        "translate": "potion.withDuration",
                                        "with": [
                                            {
                                                "translate": "potion.withAmplifier",
                                                "with": [
                                                    {
                                                        "translate": "effect.minecraft.speed"
                                                    },
                                                    {
                                                        "translate": "potion.potency.2"
                                                    }
                                                ]
                                            },
                                            "0:16"
                                        ],
                                        "color": "blue",
                                        "italic": false
                                    }
                                ]
                            ],
```

2021-07-18 05:19 UTC, BluePsychoRanger commented on gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/loot_tables/recipes/potions/splash/speed.json
> +                            ],
```suggestion
                            "lore": [
                                [
                                    {
                                        "translate": "potion.withDuration",
                                        "with": [
                                            {
                                                "translate": "potion.withAmplifier",
                                                "with": [
                                                    {
                                                        "translate": "effect.minecraft.speed"
                                                    },
                                                    {
                                                        "translate": "potion.potency.3"
                                                    }
                                                ]
                                            },
                                            "3:20"
                                        ],
                                        "color": "blue",
                                        "italic": false
                                    }
                                ],
                                [
                                    {
                                        "translate": "potion.withDuration",
                                        "with": [
                                            {
                                                "translate": "potion.withAmplifier",
                                                "with": [
                                                    {
                                                        "translate": "effect.minecraft.weakness"
                                                    },
                                                    {
                                                        "translate": "potion.potency.3"
                                                    }
                                                ]
                                            },
                                            "6:00"
                                        ],
                                        "color": "blue",
                                        "italic": false
                                    }
                                ],
                                {
                                    "text": ""
                                },
                                {
                                    "translate": "potion.whenDrank",
                                    "color": "dark_purple",
                                    "italic": false
                                },
                                {
                                    "translate": "attribute.modifier.plus.1",
                                    "with": [
                                         "80",
                                         {
                                             "translate": "attribute.name.generic.movement_speed"
                                         }
                                     ],
                                     "color": "blue",
                                     "italic": false
                                },
                                {
                                    "translate": "attribute.modifier.take.0",
                                    "with": [
                                        "16",
                                        {
                                            "translate": "attribute.name.generic.attack_damage"
                                        }
                                    ],
                                    "color": "red",
                                    "italic": false
                                }
                            ],
```

2021-07-18 05:19 UTC, BluePsychoRanger commented on gm4_zauber_cauldrons/data/gm4_zauber_cauldrons/loot_tables/recipes/potions/splash/strength.json
> +                            ],
```suggestion
                            "lore": [
                                [
                                    {
                                        "translate": "potion.withDuration",
                                        "with": [
                                            {
                                                "translate": "potion.withAmplifier",
                                                "with": [
                                                    {
                                                        "translate": "effect.minecraft.strength"
                                                    },
                                                    {
                                                        "translate": "potion.potency.3"
                                                    }
                                                ]
                                            },
                                            "1:30"
                                        ],
                                        "color": "blue",
                                        "italic": false
                                    }
                                ],
                                {
                                    "text": ""
                                },
                                {
                                    "translate": "potion.whenDrank",
                                    "color": "dark_purple",
                                    "italic": false
                                },
                                {
                                    "translate": "attribute.modifier.plus.0",
                                    "with": [
                                        "12",
                                        {
                                            "translate": "attribute.name.generic.attack_damage"
                                        }
                                    ],
                                    "color": "blue",
                                    "italic": false
                                }
                            ],
```

2021-07-29 23:29 UTC, Bloo-dev commented
From my test wormholes seem to work. External testing would be appreciated.

2021-08-11 08:22 UTC, BluePsychoRanger commented
Can you make the loot tables consistent with #662 please?

2021-08-15 09:27 UTC, Bloo-dev commented
> Can you make the loot tables consistent with #663 please?

I don't think this is necessary. The loot table structure used in this module mirrors the function structure for increased readability.
Though I agree that `extra_items` is odd. I'll reorganize that before we merge this PR.

2021-08-22 19:15 UTC, merged