Sunken Treasures 1.17
Gamemode4Dev/GM4_Datapacks pull request #651
Opened 2021-07-29 20:16 UTC by BluePsychoRanger

- modified loot tables
- Fixes Squid and Guardian spawning
- make loot biome dependent
    - in oceans, rates will be very high, in rivers rates will be medium, and anywhere else rates will be low
    - in warm oceans coral can drop from sand
    - in lukewarm or warm oceans tropical fish can spawn from sand
- added gravel to sunken treasure, which has a different loot tables
- added shipwreck treasure and supply chests

New Loot Tables: https://docs.google.com/spreadsheets/d/15FemIXUjZOoXFcVOMcpTCLLPzSWevwn7fJ9mP58zRsQ/edit#gid=0

2021-08-20 14:32 UTC, Bloo-dev requested changes
Tested and code-reviewed. This looks quite good, just one minor thing caught my attention. See below.

2021-08-20 14:32 UTC, Bloo-dev commented on gm4_sunken_treasure/data/gm4_sunken_treasure/functions/tick.mcfunction
> +execute as @a[scores={gm4_st_gravel=1..}] at @s if predicate gm4_sunken_treasure:in_deep_water anchored eyes positioned ^ ^ ^2 at @e[type=minecraft:item,limit=1,distance=..2.5,nbt={Item:{id:"minecraf
These lines should be combined into a function call that then checks for the item. This will reduce the amount of commands run per tick.

2021-08-21 17:44 UTC, misode reviewed
Not a complete review but a few minor issues

2021-08-23 20:10 UTC, BluePsychoRanger commented
I've made these changes

2021-09-05 09:57 UTC, Bloo-dev approved these changes

2021-09-08 10:21 UTC, merged