Rewrite and enhance the Undead Players module
Gamemode4Dev/GM4_Datapacks pull request #653
Opened 2021-07-30 23:00 UTC by Luewd

Bugfixes:
 - Undead player will no longer spawn in unusual locations (such as player respawn point). Using advancement triggers, it will now spawn *immediately* instead of up to 15 ticks late.

Enhancements:
 - Undead player name now includes the player name ("Undead Sparks").
 - Undead player that drowns will now keep armor and weapon.

2021-08-02 15:53 UTC, misode requested changes
Well structured and documented. Tested and works fine.

2021-08-02 15:53 UTC, misode commented on gm4_undead_players/data/gm4_undead_players/functions/check_drowning.mcfunction
> +execute if score #conversion_time gm4_undead_drown matches 0.. run function gm4_undead_players:process_drowning
Instead of this intermediate function, you can check `nbt=!{DrownedConversionTime:-1}` in `main`.

2021-08-02 15:53 UTC, misode commented on gm4_undead_players/data/gm4_undead_players/functions/init_drowned.mcfunction
> +tag @s remove gm4_undead_players_new
Typo. This should be `gm4_undead_player_new`.

2021-08-03 19:52 UTC, misode approved these changes

2021-08-10 10:33 UTC, Bloo-dev approved these changes
Very clean implementation, ready to be merged.

2021-08-20 14:43 UTC, merged