LiaB: Adds Potion Liquids compat
Gamemode4Dev/GM4_Datapacks pull request #712
Opened 2021-12-01 00:17 UTC by EpyonProjects

- Lightning Tanks!
- Illusioners are milkable for:
  - Invisibility
  - Blindness
  - Night Vision
- Potion durations modified

2021-12-01 21:05 UTC, Bloo-dev commented
> Illusioners are milkable for:
Invisibility
Blindness
Night Vision

I went back and forth on this so here's my final verdict; I don't think this makes a lot of sense. With witches it's a different situation cause the witches do have potion bottles, so you're basically holding them hostage and they give you the content of those bottles.
Illusioners casts spells, not potions -- so it doesn't make sense to get potions from them.

2021-12-01 22:17 UTC, misode commented on .vscode/settings.json
> -	"datapack.env.jsonVersion": "1.17",
Remove these lines

2021-12-26 21:05 UTC, SpecialBuilder32 requested changes
So I tested this and it doesn't work currently. empty_bottle -> LiAB does not work right now. I attached the reason why below. 

So why do you have the functions for LIAB split between the potion_liquids and the liquid_tanks namespaces? It makes this really confusing to read, and doesn't make alot of sense? You should pick one and stick all the functions under that. Personally I thought it should just be a base interaction, not a potion liquids interaction but perhaps I missed some other discussion about it. standard_liquids does things like water bottles and ink, and those are pretty potion-like.


Okay, now some other generic LIAB comments, since I didn't have a chance to review the module originally. 

1. There should be a sound effect for when a liab is "brewed" in the brewing stand, similar to vanilla's bubbly sound effect. I played around with some sounds and got this, but it's not great. 

```playsound minecraft:block.brewing_stand.brew master @s ~ ~ ~ 1 1
playsound minecraft:block.respawn_anchor.set_spawn master @s ~ ~ ~ 0.41 1.65
playsound minecraft:block.bell.resonate master @s ~ ~ ~ 1 1.58```

2. Similarly, I think block-animating should get a sound effect, shulker spawns and such. Perhaps the zombie_villager.conversion would be good.

2021-12-26 21:06 UTC, EpyonProjects commented on gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/potion_liquids/liquid_init/lightning.mcfunction
> +summon armor_stand ~ ~-.45 ~ {CustomName:'"gm4_liquid_tank_display"',Tags:["gm4_no_edit","gm4_liquid_tank_display"],NoGravity:1,Marker:1,Silent:1,Invisible:1,Invulnerable:1,Small:1,DisabledSlots:2039
Memo literally made the texture, so I don't know what that's about :/

2021-12-26 21:07 UTC, EpyonProjects commented on gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/liquid_tanks/util/lightning.mcfunction
> +playsound entity.player.swim block @a[distance=..8] ~ ~ ~ .5 1.5
Just default, but also you can't hear it over the LOUD lightning sound :P

2021-12-26 21:09 UTC, Bloo-dev commented on gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/potion_liquids/liquid_init/lightning.mcfunction
> +summon armor_stand ~ ~-.45 ~ {CustomName:'"gm4_liquid_tank_display"',Tags:["gm4_no_edit","gm4_liquid_tank_display"],NoGravity:1,Marker:1,Silent:1,Invisible:1,Invulnerable:1,Small:1,DisabledSlots:2039
It's probably generated by [mineskin.org](mineskin.org).

2022-01-25 21:04 UTC, SpecialBuilder32 commented on gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/liquid_tanks/util/lightning.mcfunction
> +playsound entity.player.swim block @a[distance=..8] ~ ~ ~ .5 1.5
Nothing better has come to mind in the past month, so this is fine.

2022-01-25 21:11 UTC, SpecialBuilder32 approved these changes
Took another look over the code and tested ingame again. It all looks good. Approved to merge :+1:

2022-01-29 10:39 UTC, Bloo-dev commented on gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/functions/liquid_tanks/util/lightning.mcfunction
> +playsound entity.player.swim block @a[distance=..8] ~ ~ ~ .5 1.5
Added a better sound.

2022-01-29 10:52 UTC, Bloo-dev commented on gm4_lightning_in_a_bottle/data/gm4_lightning_in_a_bottle/loot_tables/items/bottle_of_lightning.json
> +                    "translate": "item.gm4.bottle.effect.lightning"
I don't like this, but I won't oppose it.

2022-01-29 10:53 UTC, Bloo-dev approved these changes
Did a full code review on this, this is ready merge.

2022-01-29 10:54 UTC, merged