Hotswap Hotbars
Gamemode4Dev/GM4_Datapacks pull request #850
Opened 2023-02-19 04:39 UTC by BluePsychoRanger

New module (name subject to change)
description todo

2023-03-22 20:35 UTC, EpyonProjects commented
Downloaded the artifact, tested in 1.19.4.  Works great, feels seamless, can't seem to find any issues 👍

2023-03-23 12:17 UTC, TheThanathor reviewed
Left a few minor points. Code looks good, and the module feels great to use in-game.
It could be be updated with the new 1.19.4 features before release, but that's not at all necessary.

What could be added is a custom texture for the Hotswapper (especially the firework form), kyrkis is looking for something to work on, so you can ask him to make something.

2023-03-23 12:17 UTC, TheThanathor commented on gm4_hotswap_hotbars/data/gm4_hotswap_hotbars/functions/swap/restore_box.mcfunction
> +
seems to be a debug message left
```suggestion

```

2023-03-23 12:17 UTC, TheThanathor commented on gm4_hotswap_hotbars/data/gm4_hotswap_hotbars/tags/items/shulker_boxes.json
> +
```suggestion
    "minecraft:black_shulker_box",
    "minecraft:blue_shulker_box",
    "minecraft:brown_shulker_box",
    "minecraft:cyan_shulker_box",
    "minecraft:gray_shulker_box",
    "minecraft:green_shulker_box",
    "minecraft:light_blue_shulker_box",
    "minecraft:light_gray_shulker_box",
    "minecraft:lime_shulker_box",
    "minecraft:magenta_shulker_box",
    "minecraft:orange_shulker_box",
    "minecraft:pink_shulker_box",
    "minecraft:purple_shulker_box",
    "minecraft:red_shulker_box",
    "minecraft:shulker_box",
    "minecraft:white_shulker_box",
    "minecraft:yellow_shulker_box"
```

2023-07-03 19:21 UTC, TheThanathor commented
tested in 1.20, works as expected and was unable to break anything

2023-07-10 21:02 UTC, TheThanathor commented
Notes after some playtesting:
- conserve colour during crafting
- don't allow storing of shulker boxes or hotswappers in firework star form inside hotswappers (really easy to chunk ban an area), instead drop the item at the players feet with 0 PickupDelay
- don't HideFlags the contents of the shulkerbox
- crafting recipe might need tweaking

2023-07-25 01:21 UTC, BluePsychoRanger commented
I've made the changes outlined in Thanathor's latest post. The recipe tweak hasn't been made since that's waiting for further discussion on discord. I didn't (and currently can't) test the changes, so if someone could see if the following works that'd be great:
- When crafting, the color of the shulker box doesn't change (test with all colors)
- When there are items in the hotswapper, the advanced tooltips say what the items are (just like a normal shulker box)
- Trying to swap a shulker box and/or hotswapper firework star into a new hotbar results in those items being dropped at the player's feet (I forgot how to obtain the firework star item, but there is a minor, non-destructive exploit to get it in the inventory)

2023-11-22 12:33 UTC, Bloo-dev commented
Update on this for future us:
This is still being worked on but has dropped on the priority list (to make space for more important projects such as the Guidebook).

At some point this will need to be tested & potentially updated to be compatible with newer minecraft versions.

2023-12-17 03:38 UTC, BluePsychoRanger commented
This has had a few updates, notably the crafting recipe has been changed (see below) and the name of the item was changed to "Mechanical Shulker Box." Additionally, a dupe bug that was introduced in the commit to prevent hotswappers and shulker boxes to be stored was squished. Also, now it properly hides the color data of the firework star when it's in the offhand.

I've tested it for 1.20.2 and I didn't see anything that'd break in 1.20.3-1.20.4, though if someone would like to test it, that'd be awesome.

2023-12-17 04:39 UTC, BluePsychoRanger commented
New recipe
<img width="85" alt="recipe" src="https://github.com/Gamemode4Dev/GM4_Datapacks/assets/40612230/98160b6b-6e41-4932-bdc3-8a294c65316f">

2024-01-04 12:37 UTC, Bloo-dev requested changes
I tested this in-game and found a couple of issues.

Loss of custom data (breaking):
1. Be in survival mode and have a hotswapper in your hotbar
2. Place the hotswapper
3. Break it by hand
4. ❌ The hotswapper loses all its custom data; It is now called 'Customize Hotbars' and no longer becomes a firework star when placed in the offhand.

Wooden swords visuals:
1. Have a hotswapper in your offhand, with some items inside
2. Press the offhand key (`F` by default) whilst looking down
3. ❌ You can see wooden swords spawning in for a split second, additionally, if you do this on a hopper the hopper will steal your items (but those items wont be wooden swords)

2024-07-21 11:28 UTC, Bloo-dev commented
This PR is outdated, as it does not support 1.21.

2025-05-26 20:10 UTC, Bloo-dev commented
Closing this as at this point, a full re-write is probably easier. We are still interested in making this concept a module, however.

2025-05-26 20:10 UTC, closed without merging