CE 1.19.4 update
Gamemode4Dev/GM4_Datapacks pull request #859
Opened 2023-03-22 15:08 UTC by TheThanathor

**Technical**
- [x] use new damage command
- [ ] use new biome command
- [ ] update effect particles to match the new effect colour
- [ ] translate changes
- [ ] use effect infinite duration where applicable
- [ ] use execute summon where applicable
- [ ] use execute target for weapon / mob attacks with effects (maybe, check if this works the same)
- [ ] check predicate changes (removal of damage type predicates)
- [ ] add sniffer to entity tags where needed
- [ ] add cherry grove to Mountainous+Growth biome type (this is a new combo, so check for problems)

**Armor**
- [ ] Reverberating buff
- [ ] Consume count all kills obtained in clock cycle instead of one
- [ ] Fix Challenger armor losing enchants
- [ ] Fix Vorpal TP (already in the server version)
- [ ] Rework Trade armor (pocket horse?)
- [ ] Focused buff (double effect)
- [ ] Berserkers buff (also increase attack speed)
- [ ] Poised rework
- [ ] Solid buff (+1/2 armor when active)
- [ ] Lunar buff

**Mobs**
- [ ] Increase Shovel / Pickaxe rates
- [ ] Disable bonus endermen health in the end (for farms)

**Weapons**
- [ ] Reverberating buff
- [ ] Fix enchantments being added to previous enchantments upon identification (Flaming)
- [ ] Yearning nerf (remove damage buff)
- [ ] Swift buff (double attack speed increase)

2023-03-22 22:00 UTC, misode commented
@TheThanathor Could you make a separate PR for bugfixes (making the module work in 1.19.4) and feature changes/code optimizations using the new features?

2023-07-24 20:03 UTC, SpecialBuilder32 requested changes
Developer/Admin tools:
- I did a peek at the code and while it doesn't look *terribly* easy, it would be nice to have a set of loot tables or functions that can give you each of the weapon/armor types. I think it would be fine if it was limited to the iron material as well, to help reduce needed functions

Other than that, I spot-checked what changes I could and found no functional issues. Browsing through the code also looks good, but I suspect this is a module large enough that any lingering issues will just have to be encountered live. 

Before we merge this update, I would love if you could add a Readme and update the wiki page; You're the only one who could know what to write on both.

2023-07-27 20:35 UTC, TheThanathor commented
README (and hopefully icon) will come this weekend

2023-09-08 13:18 UTC, Bloo-dev commented
I will do a in-game test of this later today, once it passes that this should be ok to merge.

2023-09-08 22:17 UTC, Bloo-dev commented
I did some in-game testing and mobs do spawn with the proper gear and effects. Identifying gear also works.

I did not do a full test of the module, nor a full code review.

2023-09-08 22:17 UTC, Bloo-dev approved these changes
I did some in-game testing and mobs do spawn with the proper gear and effects. Identifying gear also works.

I did not do a full test of the module due to the scale of the module, nor a full code review.

2023-09-22 22:25 UTC, SpecialBuilder32 approved these changes

2023-09-22 22:26 UTC, merged