lib trees: Reduce selectors in tick
Gamemode4Dev/GM4_Datapacks pull request #989
Opened 2024-03-17 20:38 UTC by EpyonProjects

Currently has 3 `@e` selectors in a tick clock.  This function is usually the highest percentage of the tick on the Public Server.

2024-03-17 20:39 UTC, misode commented
I'm not 100% sure this will improve performance, so please test and profile this on the server

2024-03-17 20:40 UTC, EpyonProjects commented
That was the goal!  We have a _lot_ of markers and the entity count is very high.  Just a quick test doesn't hurt

2024-03-18 01:42 UTC, misode requested changes

2024-03-18 01:42 UTC, misode commented on lib_trees/data/gm4_trees/functions/tick.mcfunction
> +execute as @e[type=marker,tag=gm4_tree_sapling] run function gm4_trees:sapling/process
Missing `at @s`

2024-03-18 01:46 UTC, misode approved these changes

2024-03-19 21:46 UTC, merged